apiVersion: v1
entries:
  cluster-api-visualizer:
  - apiVersion: v2
    appVersion: v1.4.0
    created: "2024-12-12T01:50:16.540384916Z"
    description: A Helm Chart for installing the Cluster API Visualizer
    digest: 3eb4cf6f4f399434bf76e12e0b01a94b5c174259d1574a7387b6bc4215f3d941
    maintainers:
    - email: jt572@cornell.edu
      name: Jonathan Tong
    name: cluster-api-visualizer
    sources:
    - https://github.com/Jont828/cluster-api-visualizer
    type: application
    urls:
    - https://Jont828.github.io/cluster-api-visualizer/charts/cluster-api-visualizer-1.4.0.tgz
    version: 1.4.0
  - apiVersion: v2
    appVersion: v1.3.1
    created: "2024-11-25T21:47:00.990527973Z"
    description: A Helm Chart for installing the Cluster API Visualizer
    digest: 00471c90deacee0b6d4f0b26b0b7fcd2e96b43a8d00d500c52ce55b5cda83d38
    maintainers:
    - email: jt572@cornell.edu
      name: Jonathan Tong
    name: cluster-api-visualizer
    sources:
    - https://github.com/Jont828/cluster-api-visualizer
    type: application
    urls:
    - https://Jont828.github.io/cluster-api-visualizer/charts/cluster-api-visualizer-1.3.2.tgz
    version: 1.3.2
  - apiVersion: v2
    appVersion: v1.3.1
    created: "2024-06-20T19:21:39.481260176Z"
    description: A Helm Chart for installing the Cluster API Visualizer
    digest: 830fac8c8dd6bd6e6a8b46c61b3f61fbaa8239d0068336b23a99cb7adb90f335
    maintainers:
    - email: jt572@cornell.edu
      name: Jonathan Tong
    name: cluster-api-visualizer
    sources:
    - https://github.com/Jont828/cluster-api-visualizer
    type: application
    urls:
    - https://Jont828.github.io/cluster-api-visualizer/charts/cluster-api-visualizer-1.3.1.tgz
    version: 1.3.1
  - apiVersion: v2
    appVersion: v1.3.0
    created: "2024-06-20T18:55:23.011967911Z"
    description: A Helm Chart for installing the Cluster API Visualizer
    digest: 5e64d805f88282d21c9dc0fdaad64a38c4372ca3e0dee9a703fcffa395877aec
    maintainers:
    - email: jt572@cornell.edu
      name: Jonathan Tong
    name: cluster-api-visualizer
    sources:
    - https://github.com/Jont828/cluster-api-visualizer
    type: application
    urls:
    - https://Jont828.github.io/cluster-api-visualizer/charts/cluster-api-visualizer-1.3.0.tgz
    version: 1.3.0
  - apiVersion: v2
    appVersion: v1.2.0
    created: "2023-08-15T23:25:13.453291566Z"
    description: A Helm Chart for installing the Cluster API Visualizer
    digest: 81de4d08b7dd74a0b4a0a888b1ba076f7c50056ea9bfbbc3fa8bfdab04000054
    maintainers:
    - email: jt572@cornell.edu
      name: Jonathan Tong
    name: cluster-api-visualizer
    sources:
    - https://github.com/Jont828/cluster-api-visualizer
    type: application
    urls:
    - https://Jont828.github.io/cluster-api-visualizer/charts/cluster-api-visualizer-1.2.0.tgz
    version: 1.2.0
  - apiVersion: v2
    appVersion: v1.1.1
    created: "2023-08-15T00:33:01.072177583Z"
    description: A Helm Chart for installing the Cluster API Visualizer
    digest: aaaa83fdbc4b9263727763076bde9e6126527c6c9820a85e425e47b5ef6f028d
    maintainers:
    - email: jt572@cornell.edu
      name: Jonathan Tong
    name: cluster-api-visualizer
    sources:
    - https://github.com/Jont828/cluster-api-visualizer
    type: application
    urls:
    - https://Jont828.github.io/cluster-api-visualizer/charts/cluster-api-visualizer-1.1.1.tgz
    version: 1.1.1
  - apiVersion: v2
    appVersion: v1.1.0
    created: "2023-01-05T17:15:47.50716092Z"
    description: A Helm Chart for installing the Cluster API Visualizer
    digest: 71853a6505442658b167d2564740d1ed83f1feb23b66256e589375701b28c5c5
    maintainers:
    - email: jt572@cornell.edu
      name: Jonathan Tong
    name: cluster-api-visualizer
    sources:
    - https://github.com/Jont828/cluster-api-visualizer
    type: application
    urls:
    - https://Jont828.github.io/cluster-api-visualizer/charts/cluster-api-visualizer-1.1.0.tgz
    version: 1.1.0
  - apiVersion: v2
    appVersion: v1.0.2
    created: "2022-12-13T22:35:51.125330592Z"
    description: A Helm Chart for installing the Cluster API Visualizer
    digest: 50471d47197d557ede6f81a95bb9d7abfdf681011d4f771f165c52c64638ab6b
    maintainers:
    - email: jt572@cornell.edu
      name: Jonathan Tong
    name: cluster-api-visualizer
    sources:
    - https://github.com/Jont828/cluster-api-visualizer
    type: application
    urls:
    - https://Jont828.github.io/cluster-api-visualizer/charts/cluster-api-visualizer-1.0.2.tgz
    version: 1.0.2
  - apiVersion: v2
    appVersion: v1.0.1
    created: "2022-10-19T00:24:56.648584722Z"
    description: A Helm Chart for installing the Cluster API Visualizer
    digest: 4703305ada4dcda060cd23da16c8df257cf8fbcf67dfaf516256ad50508ed7cb
    maintainers:
    - email: jt572@cornell.edu
      name: Jonathan Tong
    name: cluster-api-visualizer
    sources:
    - https://github.com/Jont828/cluster-api-visualizer
    type: application
    urls:
    - https://Jont828.github.io/cluster-api-visualizer/charts/cluster-api-visualizer-1.0.1.tgz
    version: 1.0.1
  - apiVersion: v2
    appVersion: v1.0.0
    created: "2022-07-26T23:54:58.380155326Z"
    description: A Helm Chart for installing the Cluster API Visualizer
    digest: 184ae6d41e588b1d5d5fc02e90f4dd7b933f2a63adfe33a38b1a13cab222f601
    maintainers:
    - email: jt572@cornell.edu
      name: Jonathan Tong
    name: cluster-api-visualizer
    sources:
    - https://github.com/Jont828/cluster-api-visualizer
    type: application
    urls:
    - https://Jont828.github.io/cluster-api-visualizer/charts/cluster-api-visualizer-1.0.0.tgz
    version: 1.0.0
  - apiVersion: v2
    appVersion: v0.1.0-alpha.2
    created: "2022-07-26T23:22:50.692011692Z"
    description: A Helm Chart for installing the Cluster API Visualizer
    digest: 8a1ba01899bbbf25e2d372693105e5f25d270a84777ba505e25653988b79fe08
    maintainers:
    - email: jt572@cornell.edu
      name: Jonathan Tong
    name: cluster-api-visualizer
    sources:
    - https://github.com/Jont828/cluster-api-visualizer
    type: application
    urls:
    - https://Jont828.github.io/cluster-api-visualizer/charts/cluster-api-visualizer-0.1.1.tgz
    version: 0.1.1
generated: "2024-12-12T01:50:16.540014986Z"
